schema = 3

[mod]
  [mod."github.com/Jorropo/jsync"]
    version = "v1.0.1"
    hash = "sha256-r1MW9Nu5WYMBAG1brgyZie7QF/IEeeq52rt647mxNug="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20231202071711-9a357b53e9c9"
    hash = "sha256-nOY+C6mkdVA38WHiwUgmsMJO7YzQJZ9yD3cZcQM7iio="
  [mod."github.com/benbjohnson/clock"]
    version = "v1.3.5"
    hash = "sha256-pSTHNILoQpLL64bvdcNwXv+dVJ3LBZRoECpj7m8C9tw="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/blang/semver/v4"]
    version = "v4.0.0"
    hash = "sha256-dJC22MjnfT5WqJ7x7Tc3Bvpw9tFnBn9HqfWFiM57JVc="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/containerd/cgroups"]
    version = "v1.1.0"
    hash = "sha256-86t3du0TVwGMDIX6XMX9VPTho4h00nBepdm1wPVGNK4="
  [mod."github.com/coreos/go-systemd/v22"]
    version = "v22.5.0"
    hash = "sha256-E2zXikbmIQImghstLUWuey1YgA0Folu3F+fi5k4hCxA="
  [mod."github.com/crackcomm/go-gitignore"]
    version = "v0.0.0-20231225121904-e25f5bc08668"
    hash = "sha256-XsnVBh1ZQIQAVmJXdid/xd5ONtRTrCxSOftXzQ0FwzA="
  [mod."github.com/cskr/pubsub"]
    version = "v1.0.2"
    hash = "sha256-Lsk/IM8XCyErOhwfhiDCqcdy58Yt5TFeT5/mrspjKHM="
  [mod."github.com/davidlazar/go-crypto"]
    version = "v0.0.0-20200604182044-b73af7476f6c"
    hash = "sha256-aDgsk+QsLgtbUHDuq44fDDcA8DNxqyX+4xqiqRWCi4I="
  [mod."github.com/dcnetio/ipfs-lite"]
    version = "v1.1.13"
    hash = "sha256-GBfq6NIfQl8dWk6EhFgI++NT91LL0nstxOphDjxL1pU="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.3.0"
    hash = "sha256-ADbhI5Ad+q3OxooIiYeLAq5mMONk1gPIAnTch9zKsIM="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/elastic/gosigar"]
    version = "v0.14.2"
    hash = "sha256-zIrTrgtCRJP2tqW71EJan+JdLqPCANtumWTEURPMbjw="
  [mod."github.com/facebookgo/atomicfile"]
    version = "v0.0.0-20151019160806-2de1f203e7d5"
    hash = "sha256-Zgu5YTeVIz1wgKi13l07A4Rd8l26Iobl7jIA4002Xe8="
  [mod."github.com/flynn/noise"]
    version = "v1.1.0"
    hash = "sha256-gHCdm9oJTKO+aUGWCw9LM/WHrZT2K6C5+j7VLXpqK48="
  [mod."github.com/francoispqt/gojay"]
    version = "v1.2.13"
    hash = "sha256-BrRZd2lEF5CQVmUTLW9AwQ0DY5ZbFJ8c7NVJ5Rsuqcc="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.1"
    hash = "sha256-WM4badoqxXlBmqCRrnmtNce63dLlr/FJav3BJSYHvaY="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-task/slim-sprig"]
    version = "v0.0.0-20230315185526-52ccab3ef572"
    hash = "sha256-D6NjCQbcYC53NdwzyAm4i9M1OjTJIVu4EIt3AD/Vxfg="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.3"
    hash = "sha256-ZOzfwCXh+qp+hp+UnC0t422hUV0Cq5KANXkx8hcLp7s="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.0"
    hash = "sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/google/gopacket"]
    version = "v1.1.19"
    hash = "sha256-EueA6b+c7SWJjII3HiFnMMKj3mIbAdzboJo6HBZnkkc="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20240509144519-723abb6459b7"
    hash = "sha256-Kupw9/fbR9ZdnmCPJF8mVJTvWDO74J0+sJ8es5V8CPY="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.1"
    hash = "sha256-eHZ/U+eeE5tSgWc1jEDuBwtTRbXKP9fqP9zfW4Zw8T0="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v1.0.2"
    hash = "sha256-yy+5botc6T5wXgOe2mfNXJP3wr+MkVlUZ2JBkmmrA48="
  [mod."github.com/hashicorp/golang-lru/v2"]
    version = "v2.0.7"
    hash = "sha256-t1bcXLgrQNOYUVyYEZ0knxcXpsTk4IuJZDjKvyJX75g="
  [mod."github.com/huin/goupnp"]
    version = "v1.3.0"
    hash = "sha256-/VTfjUhHLGuXymYBC1vQJv1N8O1AjYwC/xTGd6h3Uw0="
  [mod."github.com/ipfs/bbloom"]
    version = "v0.0.4"
    hash = "sha256-4k778kBlNul2Rc4xuNQ9WA4kT0V7x5X9odZrT+2xjTU="
  [mod."github.com/ipfs/boxo"]
    version = "v0.20.0"
    hash = "sha256-Ce2qyu3avJ5i05zbmEU8vjK78OXNwlVefmdB+26NtN4="
  [mod."github.com/ipfs/go-bitfield"]
    version = "v1.1.0"
    hash = "sha256-wxiN3ajYwH6VvYGiz9QVrVGe+QW34LQgmPDHKV7jD/4="
  [mod."github.com/ipfs/go-block-format"]
    version = "v0.2.0"
    hash = "sha256-36rci5EyL9Vx6QmLldaswhuDAR/xOcHHEyJpbQDnqF0="
  [mod."github.com/ipfs/go-cid"]
    version = "v0.4.1"
    hash = "sha256-QygRTLQBk8tPQVs3k1m5koinkZtTRKWyakJCDV4rzT0="
  [mod."github.com/ipfs/go-cidutil"]
    version = "v0.1.0"
    hash = "sha256-NtS7YelOiBeLN5SnZcjbj3cst9RyNekEzLm7LIjjKEg="
  [mod."github.com/ipfs/go-datastore"]
    version = "v0.6.0"
    hash = "sha256-78/VQtKeA0AAvABAiAp0OTD5t6mn4kPlCdhJZoBy7/o="
  [mod."github.com/ipfs/go-ds-measure"]
    version = "v0.2.0"
    hash = "sha256-ixSXKBlH/bMHe1Vtlts4LXtx/H6WLj47DgiGpQMy45I="
  [mod."github.com/ipfs/go-fs-lock"]
    version = "v0.0.7"
    hash = "sha256-/1nNpdeZB0N5L0BVC15cAl5U/SsQNU584zcVeTATxf0="
  [mod."github.com/ipfs/go-ipfs-cmds"]
    version = "v0.11.0"
    hash = "sha256-7idCq7F+m8ZJo88XuG0JxEn47Yjm2kW/Pot4c59aOgc="
  [mod."github.com/ipfs/go-ipfs-delay"]
    version = "v0.0.1"
    hash = "sha256-PO6LIwGMEIITpBxY1YLX1iBIlK8jIWhXhGFqIYxkqig="
  [mod."github.com/ipfs/go-ipfs-pq"]
    version = "v0.0.3"
    hash = "sha256-BG0QN1TCxVjbl2H5EGWUu4tMOOse0HTVF8447ek5IX4="
  [mod."github.com/ipfs/go-ipfs-util"]
    version = "v0.0.3"
    hash = "sha256-pO+XQc9EnV5mKE7WagePl88uvk5jgd7HIZt9UJRhAHU="
  [mod."github.com/ipfs/go-ipld-cbor"]
    version = "v0.1.0"
    hash = "sha256-QcCEHj8STlVaW1YODb7amCcCwIDj3/+jUmm64JYms3s="
  [mod."github.com/ipfs/go-ipld-format"]
    version = "v0.6.0"
    hash = "sha256-7Fg/Rd/7ghuGnlV59wmnL9V+zggStHHFLzD1yqw4gX4="
  [mod."github.com/ipfs/go-ipld-legacy"]
    version = "v0.2.1"
    hash = "sha256-oBTTox/Jfoh2zizYHrn1AUKJaHa3ceu/A8N3Twf7gmk="
  [mod."github.com/ipfs/go-log"]
    version = "v1.0.5"
    hash = "sha256-WQarHZo2y/rH6ixLsOlN5fFZeLUqsOTMnvdxszP2Qj4="
  [mod."github.com/ipfs/go-log/v2"]
    version = "v2.5.1"
    hash = "sha256-CqujRB8/Cf0N7GwEtpxp0kI+UuA4I4ggMcNfOxHXA/o="
  [mod."github.com/ipfs/go-metrics-interface"]
    version = "v0.0.1"
    hash = "sha256-/vXCR/eiNvPMB0ToDWN6atmnpDGAr/kjxdbpckI4rCc="
  [mod."github.com/ipfs/go-peertaskqueue"]
    version = "v0.8.1"
    hash = "sha256-+A1W45/HLhPyEvbdPLQ5cEKkJrlcxdbDmyNJo0EzJOw="
  [mod."github.com/ipfs/go-unixfsnode"]
    version = "v1.9.0"
    hash = "sha256-o8PxyQ5U2ciXT41SaXAnFqCloILm0DvXVfxqUuQPgt4="
  [mod."github.com/ipfs/kubo"]
    version = "v0.29.0"
    hash = "sha256-CbgSlk9Opj531a7IolHfsq9ZRrDMz003uLuz1p2QpRs="
  [mod."github.com/ipld/go-car/v2"]
    version = "v2.13.1"
    hash = "sha256-I09RzdAd97OI+zstGEvBXDwHm2NKSwVXWCwAxtZrolY="
  [mod."github.com/ipld/go-codec-dagpb"]
    version = "v1.6.0"
    hash = "sha256-eO6F8o2g1JXYwQ3ejaZRUjNQhlzUtVdS1FwIkd/ieck="
  [mod."github.com/ipld/go-ipld-prime"]
    version = "v0.21.0"
    hash = "sha256-aOLwqmDtt3jA4Fb3U+FOBX6T0yOMujuVInJN2a+7iSA="
  [mod."github.com/jackpal/go-nat-pmp"]
    version = "v1.0.2"
    hash = "sha256-L1D4Yoxnzihs795GZ+Q3AZsFP5c4iqyjTeyrudzPXtw="
  [mod."github.com/jbenet/go-temp-err-catcher"]
    version = "v0.1.0"
    hash = "sha256-+SSoW7g/ADswuIS4AyVEp3+cH8KzByHlIJhLA6EUiFg="
  [mod."github.com/jbenet/goprocess"]
    version = "v0.1.4"
    hash = "sha256-U8K2bPDD8xkc+EcDMRpTaCcHN/jfsHvEYQLO1Kcuivw="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.8"
    hash = "sha256-8rgCCfHX29le8m6fyVn6gwFde5TPUHjwQqZqv9JIubs="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.7"
    hash = "sha256-bjinp7b7qWk+DcZDDv1EedJxZqGxp2NWY+NYKBfE5xU="
  [mod."github.com/koron/go-ssdp"]
    version = "v0.0.4"
    hash = "sha256-jjh1CnkjEgFju//kJwAFrsIX9sGS667N5A/azenv/yk="
  [mod."github.com/lestrrat-go/blackmagic"]
    version = "v1.0.2"
    hash = "sha256-rdvRe733uk5uCBhrmHgkjvQH40yE+C/2l1rVYfHl5aw="
  [mod."github.com/lestrrat-go/httpcc"]
    version = "v1.0.1"
    hash = "sha256-SMRSwJpqDIs/xL0l2e8vP0W65qtCHX2wigcOeqPJmos="
  [mod."github.com/lestrrat-go/httprc"]
    version = "v1.0.5"
    hash = "sha256-8+VtO22/V9eyKSyZr2udOX8h7dDX0jrrvcXcHyq1VJE="
  [mod."github.com/lestrrat-go/iter"]
    version = "v1.0.2"
    hash = "sha256-30tErRf7Qu/NOAt1YURXY/XJSA6sCr6hYQfO8QqHrtw="
  [mod."github.com/lestrrat-go/jwx/v2"]
    version = "v2.1.0"
    hash = "sha256-LHAOe+SV5XkzfG28UQLQwdriQ5g+nDlXVHBJjvA5SBc="
  [mod."github.com/lestrrat-go/option"]
    version = "v1.0.1"
    hash = "sha256-jVcIYYVsxElIS/l2akEw32vdEPR8+anR6oeT1FoYULI="
  [mod."github.com/libp2p/go-buffer-pool"]
    version = "v0.1.0"
    hash = "sha256-wQqGTtRWsfR9n0O/SXHVgECebbnNmHddxJIbG63OJBQ="
  [mod."github.com/libp2p/go-cidranger"]
    version = "v1.1.0"
    hash = "sha256-aqk225oAthKAvCbtsLNH8CwMcmYBj2x/URafDsukHxY="
  [mod."github.com/libp2p/go-flow-metrics"]
    version = "v0.1.0"
    hash = "sha256-0AhjqJHOawVHURHguVLyhnYHbzsBSllBbF9Yljcyy48="
  [mod."github.com/libp2p/go-libp2p"]
    version = "v0.34.1"
    hash = "sha256-LbqbEKZ2SZ/fOa/+C+PUDZrs8mHXk7VqjAQ5P9YWsw0="
  [mod."github.com/libp2p/go-libp2p-asn-util"]
    version = "v0.4.1"
    hash = "sha256-J1+ePyBarLdD1cVo8B374xcfvcuOUUoJuDPQNQjWJLE="
  [mod."github.com/libp2p/go-libp2p-kad-dht"]
    version = "v0.25.2"
    hash = "sha256-wVK0//p1q3+YJPBZaF15Ammut3jN7hFXhSfW9UppoIA="
  [mod."github.com/libp2p/go-libp2p-kbucket"]
    version = "v0.6.3"
    hash = "sha256-hWjVDoc/5V+Yx7IzDlr2fX60w3ffr82t7U6IXah+LbU="
  [mod."github.com/libp2p/go-libp2p-record"]
    version = "v0.2.0"
    hash = "sha256-5KJawe6Q8JOzH8/qq6vt1DEJQ3vHk6AgxLd5sFADVn4="
  [mod."github.com/libp2p/go-libp2p-routing-helpers"]
    version = "v0.7.3"
    hash = "sha256-M7WWrby5R43fqKPethPUgRvVr9RxTAV8MoK2+gveF90="
  [mod."github.com/libp2p/go-msgio"]
    version = "v0.3.0"
    hash = "sha256-SYDQsX0WWRHSiytL6JDCPcbi6/edo0OQo9jpx2ZtrAA="
  [mod."github.com/libp2p/go-nat"]
    version = "v0.2.0"
    hash = "sha256-AD54zzjlwIyjPX7as+aV4SqEIKwH2lROdCe73e0cy/s="
  [mod."github.com/libp2p/go-netroute"]
    version = "v0.2.1"
    hash = "sha256-D4mSx3t5l7Cg3Xddrss4u7aqp73iu+CecLY0N4xE5ho="
  [mod."github.com/libp2p/go-reuseport"]
    version = "v0.4.0"
    hash = "sha256-RenBCRxyp43IKCFWBuByriZLhifOmXkVcJCtwGN+UwQ="
  [mod."github.com/libp2p/go-yamux/v4"]
    version = "v4.0.1"
    hash = "sha256-UggN0j755R8wtsmMbJZGeUoQSB9uLcViZgJcKZlD/Y4="
  [mod."github.com/marten-seemann/tcp"]
    version = "v0.0.0-20210406111302-dfbc87cc63fd"
    hash = "sha256-/RfByluusNJhQBF560EP9URdoW6Mfvz0CsTI0vehA1A="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/miekg/dns"]
    version = "v1.1.59"
    hash = "sha256-O8FK7gVlLB6adMl4phCH/4e923D3AU85cHthO8SWoGQ="
  [mod."github.com/mikioh/tcpinfo"]
    version = "v0.0.0-20190314235526-30a79bb1804b"
    hash = "sha256-7qDEv/9S7shWXzqbrZoIF1sXG45fwi08PRVCrujmbRQ="
  [mod."github.com/mikioh/tcpopt"]
    version = "v0.0.0-20190314235656-172688c1accc"
    hash = "sha256-Euf1BdkoiYc37obpR66425I1Xjn4wvO+cRz4mOsGueE="
  [mod."github.com/minio/blake2b-simd"]
    version = "v0.0.0-20160723061019-3f5f724cb5b1"
    hash = "sha256-rc7ozPwT59tTjs/7ERxAN4C3OoK1fdJcrQ8wYaRd0iw="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.1"
    hash = "sha256-4hfGDIQaWq8fvtGzHDhoK9v2IocXnJY7OAL6saMJbmA="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/multiformats/go-base32"]
    version = "v0.1.0"
    hash = "sha256-O2IM7FB+Y9MkDdZztyQL5F8oEnmON2Yew7XkotQziio="
  [mod."github.com/multiformats/go-base36"]
    version = "v0.2.0"
    hash = "sha256-GKNnAGA0Lb39BDGYBm1ieKdXmho8Pu7ouyfVPXvV0PE="
  [mod."github.com/multiformats/go-multiaddr"]
    version = "v0.12.4"
    hash = "sha256-CPjtobac6uvbeg3Vp/2bJ6Qk2rKfjuZ7jFRqXixpnvk="
  [mod."github.com/multiformats/go-multiaddr-dns"]
    version = "v0.3.1"
    hash = "sha256-mQhP3i8eHPkNaSqrCZ7gydhPGIyFLiVt4ybKSvtjF58="
  [mod."github.com/multiformats/go-multiaddr-fmt"]
    version = "v0.1.0"
    hash = "sha256-1SbQXGliO7tAaFoBD8mROaffxNaaKiRIjWmxD23GOIU="
  [mod."github.com/multiformats/go-multibase"]
    version = "v0.2.0"
    hash = "sha256-w+hp6u5bWyd34qe0CX+bq487ADqq6SgRR/JuqRB578s="
  [mod."github.com/multiformats/go-multicodec"]
    version = "v0.9.0"
    hash = "sha256-G3hkY/Ihw082CvFeFYwUYbjdWsRVZpvkgtzwlOaFFAw="
  [mod."github.com/multiformats/go-multihash"]
    version = "v0.2.3"
    hash = "sha256-zqIIE5jMFzm+qhUrouSF+WdXGeHUEYIQvVnKWWU6mRs="
  [mod."github.com/multiformats/go-multistream"]
    version = "v0.5.0"
    hash = "sha256-Q3gY5P4GX57z3H6WopyaUyE5a20C1LwM3iCBGE34jNY="
  [mod."github.com/multiformats/go-varint"]
    version = "v0.0.7"
    hash = "sha256-To3Uuv7uSUJEr5OTwxE1LEIpA62xY3M/KKMNlscHmlA="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.17.3"
    hash = "sha256-HKRJMYAVSVgCrLWMAMU6qqEG4K8+bwwdkzL8FGIyRS8="
  [mod."github.com/opencontainers/runtime-spec"]
    version = "v1.2.0"
    hash = "sha256-yfXm5UkBwnAz69zxyLVbEn1ZMP9yfuMISrghMN6tWoA="
  [mod."github.com/opentracing/opentracing-go"]
    version = "v1.2.0"
    hash = "sha256-kKTKFGXOsCF6QdVzI++GgaRzv2W+kWq5uDXOJChvLxM="
  [mod."github.com/pbnjay/memory"]
    version = "v0.0.0-20210728143218-7b4eea64cf58"
    hash = "sha256-QI+F1oPLOOtwNp8+m45OOoSfYFs3QVjGzE0rFdpF/IA="
  [mod."github.com/petar/GoLLRB"]
    version = "v0.0.0-20210522233825-ae3b015fd3e9"
    hash = "sha256-FkhvH+ogM8nTHyHwiRrQtrM70Xwp+1vhu9zdMyXaoEw="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/polydawn/refmt"]
    version = "v0.89.0"
    hash = "sha256-Lz82pJSiSTu8jfhub0xaSYJ/s0Rt/mGujIcPqpITCAk="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.19.1"
    hash = "sha256-MSLsMDi89uQc7Pa2fhqeamyfPJpenGj3r+eB/UotK7w="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.53.0"
    hash = "sha256-IO5DnFEYXNe5nfumAebAuiZjNaJlTiHTD0GOMqNT26o="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.0"
    hash = "sha256-XYIr/iit+c1Z1rS7LQEUo+xizCBgnDk/l9fdiQq+kqg="
  [mod."github.com/quic-go/qpack"]
    version = "v0.4.0"
    hash = "sha256-QWIumzmHD94DlNp9G3AQf9QCtF+Kv0pShT1+FH7/I/c="
  [mod."github.com/quic-go/qtls-go1-20"]
    version = "v0.3.4"
    hash = "sha256-NsefY+cj2A4w4yN0ka44MU2y/t6FbEXHU88zxMP2gzo="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.44.0"
    hash = "sha256-/y0kClY0ATBNyOAjbCjeXQEJWFWTCVktBuDO823gzV8="
  [mod."github.com/quic-go/webtransport-go"]
    version = "v0.8.0"
    hash = "sha256-J22At3m1Dp03wK/UR4guq0R1G9JrXj8nCUu8Rp4kmX8="
  [mod."github.com/raulk/go-watchdog"]
    version = "v1.3.0"
    hash = "sha256-H1D+t3cAdQVQm/YG9NjtXtSLwtTRD2XMt6x2GDG8+9Y="
  [mod."github.com/rs/cors"]
    version = "v1.10.1"
    hash = "sha256-um4INJM5/675MLK42npIsDbSQ1/Iy5ZiUNuAFReUfeM="
  [mod."github.com/samber/lo"]
    version = "v1.39.0"
    hash = "sha256-bFJXbzFpUQM2xoNrHrlzn0RJZujd21H00zGBgo/JEb0="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.0"
    hash = "sha256-zbNuKxNrUDUc6IlmRQNuJQzVe5Ol/mqp7srDg9IMMqs="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/whyrusleeping/base32"]
    version = "v0.0.0-20170828182744-c30ac30633cc"
    hash = "sha256-DlJl5zgWr2EY3OkGu30ekC3fWvpOnr0PqaPanCSSEhg="
  [mod."github.com/whyrusleeping/cbor"]
    version = "v0.0.0-20171005072247-63513f603b11"
    hash = "sha256-+pgK0asDcUxYcC55aNAf/b6WIhZhwy18PeHnh+Z/c2w="
  [mod."github.com/whyrusleeping/cbor-gen"]
    version = "v0.1.1"
    hash = "sha256-R5T34E10qg8X4oEqsYhk4OU5/1PcjhBqrEFiSMk2G5s="
  [mod."github.com/whyrusleeping/chunker"]
    version = "v0.0.0-20181014151217-fe64bd25879f"
    hash = "sha256-IkucTGx1aVXB2xQLUYfLIxxBoEEnK/wjiJ7zmC51BI8="
  [mod."github.com/whyrusleeping/go-keyspace"]
    version = "v0.0.0-20160322163242-5b898ac5add1"
    hash = "sha256-a2V0vuPSQh6d9yoxz07JNJllo1Gm1iDMC3/xjk88czo="
  [mod."go.opencensus.io"]
    version = "v0.24.0"
    hash = "sha256-4H+mGZgG2c9I1y0m8avF4qmt8LUKxxVsTqR8mKgP4yo="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.26.0"
    hash = "sha256-1LEPxggc0QK1P+Pcht1s8ySMK9eQdR7rQrkiCOtkjHI="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.26.0"
    hash = "sha256-JB3j9ggi6FK+YuKjcSdiVOJ2pnzZ2PdfVIFrpLBPmZs="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.26.0"
    hash = "sha256-n3ZTXu0Ab6RWPDDO4P21mj4dOqDKi4E/35SOHvj5aJE="
  [mod."go.uber.org/dig"]
    version = "v1.17.1"
    hash = "sha256-8TrBADTdhGQoTJ/UgiQy/kcsR6S/hZHGsGkdOwpHh6U="
  [mod."go.uber.org/fx"]
    version = "v1.21.1"
    hash = "sha256-EugSfnnfsOVqlu8vS3oLMS1WPlAfRwgashi9qAwbc3Y="
  [mod."go.uber.org/mock"]
    version = "v0.4.0"
    hash = "sha256-mJN2cPmAMTZQzOnTpJ8zi9QH2m3OAKI4IpnQW9QYS8s="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."go4.org"]
    version = "v0.0.0-20230225012048-214862532bf5"
    hash = "sha256-8y7krSESdxZfxTzo16EDqmF8USRzGmLPYr3iKuVYzzE="
  [mod."golang.org/x/crypto"]
    version = "v0.24.0"
    hash = "sha256-wpxJApwSmmn9meVdpFdOU0gzeJbIXcKuFfYUUVogSss="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240506185415-9bf2ced13842"
    hash = "sha256-5JZE4OhePWHtObIT4RJOS+2zv265Io1yJkFeE8wHXY4="
  [mod."golang.org/x/mod"]
    version = "v0.17.0"
    hash = "sha256-CLaPeF6uTFuRDv4oHwOQE6MCMvrzkUjWN3NuyywZjKU="
  [mod."golang.org/x/net"]
    version = "v0.25.0"
    hash = "sha256-IjFfXLYNj27WLF7vpkZ6mfFXBnp+7QER3OQ0RgjxN54="
  [mod."golang.org/x/sync"]
    version = "v0.7.0"
    hash = "sha256-2ETllEu2GDWoOd/yMkOkLC2hWBpKzbVZ8LhjLu0d2A8="
  [mod."golang.org/x/sys"]
    version = "v0.21.0"
    hash = "sha256-gapzPWuEqY36V6W2YhIDYR49sEvjJRd7bSuf9K1f4JY="
  [mod."golang.org/x/text"]
    version = "v0.16.0"
    hash = "sha256-hMTO45upjEuA4sJzGplJT+La2n3oAfHccfYWZuHcH+8="
  [mod."golang.org/x/tools"]
    version = "v0.21.1-0.20240508182429-e35e4ccd0d2d"
    hash = "sha256-KfnS+3fREPAWQUBoUedPupQp9yLrugxMmmEoHvyzKNE="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20231012003039-104605ab7028"
    hash = "sha256-IsFTm5WZQ6W1ZDF8WOP+6xiOAc7pIq8r9Afvkjp3PRQ="
  [mod."gonum.org/v1/gonum"]
    version = "v0.15.0"
    hash = "sha256-Q2cZkJB4F2KW6qeUOMlISWxLRh9Z8Ru16xQW7Dt/Riw="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.1"
    hash = "sha256-qnHqY6KLZiZDbTVTN6uzF4jedxROYlPCYHoiv6XI0sc="
  [mod."lukechampine.com/blake3"]
    version = "v1.3.0"
    hash = "sha256-H7ljr3coQkiNKPvn1fWm7wADu/n/PhBefTKn8UF1Wkg="
