schema = 3

[mod]
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.3.0"
    hash = "sha256-ADbhI5Ad+q3OxooIiYeLAq5mMONk1gPIAnTch9zKsIM="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.3"
    hash = "sha256-ZOzfwCXh+qp+hp+UnC0t422hUV0Cq5KANXkx8hcLp7s="
  [mod."github.com/lestrrat-go/blackmagic"]
    version = "v1.0.2"
    hash = "sha256-rdvRe733uk5uCBhrmHgkjvQH40yE+C/2l1rVYfHl5aw="
  [mod."github.com/lestrrat-go/httpcc"]
    version = "v1.0.1"
    hash = "sha256-SMRSwJpqDIs/xL0l2e8vP0W65qtCHX2wigcOeqPJmos="
  [mod."github.com/lestrrat-go/httprc"]
    version = "v1.0.5"
    hash = "sha256-8+VtO22/V9eyKSyZr2udOX8h7dDX0jrrvcXcHyq1VJE="
  [mod."github.com/lestrrat-go/iter"]
    version = "v1.0.2"
    hash = "sha256-30tErRf7Qu/NOAt1YURXY/XJSA6sCr6hYQfO8QqHrtw="
  [mod."github.com/lestrrat-go/jwx/v2"]
    version = "v2.1.0"
    hash = "sha256-LHAOe+SV5XkzfG28UQLQwdriQ5g+nDlXVHBJjvA5SBc="
  [mod."github.com/lestrrat-go/option"]
    version = "v1.0.1"
    hash = "sha256-jVcIYYVsxElIS/l2akEw32vdEPR8+anR6oeT1FoYULI="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.0"
    hash = "sha256-zbNuKxNrUDUc6IlmRQNuJQzVe5Ol/mqp7srDg9IMMqs="
  [mod."golang.org/x/crypto"]
    version = "v0.24.0"
    hash = "sha256-wpxJApwSmmn9meVdpFdOU0gzeJbIXcKuFfYUUVogSss="
  [mod."golang.org/x/sys"]
    version = "v0.21.0"
    hash = "sha256-gapzPWuEqY36V6W2YhIDYR49sEvjJRd7bSuf9K1f4JY="
